name: "NvimServer release on tag"
on:
  push:
    tags:
      - 'nvimserver-[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  Build-x86_64:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install brew packages
        run: |
          brew update >/dev/null
          brew upgrade
          brew install automake ninja coreutils
      - name: Build NvimServer
        run: |
          download_gettext=true clean=true build_libnvim=true ./NvimServer/bin/build_nvimserver.sh
      - name: Create release and upload artifact
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }}
          gh release upload ${{ github.ref_name }} .build/x86_64-apple-macosx/release/NvimServer-x86_64.tar.bz2
      - uses: actions/upload-artifact@v2
        with:
          name: NvimServer-x86_64
          path: .build/x86_64-apple-macosx/release/NvimServer-x86_64.tar.bz2
          if-no-files-found: error
          retention-days: 7

